---
- hosts: localhost
  connection: local
  tasks:
   - name: Gather only registered virtual machines
     vmware_vm_facts:
         hostname: XXXX
         username: XXXX
         password: XXXX
         vm_type: all
         validate_certs: no
     delegate_to: localhost
     register: vm_facts
